---
#destroy ec2 instances 
- hosts: localhost
  connection: local
  tasks:
    - name: Terminate Instances
      ec2_instance_facts:
        region: us-east-1
      register: ec2_info
 
    - name: displaying output
      debug: msg="{{item.instance_id}}"
      with_items: "{{ec2_info.instances}}" #this will identify and shut down all of your instancnes in your aws account BE VERY CAREFUL
 
    - name: terminate
      ec2:
        instance_ids: "{{item.instance_id}}"
        region: us-east-1
        state: absent
        wait: yes #each instancne will terminate one by one after each instannce in completed the next one will start
      with_items: "{{ec2_info.instances}}"